((c-mode .  ((indent-tabs-mode . t)
	      (tab-width . 4)
	      (c-basic-offset . 4)
	      (c-file-offsets . ((block-open . 0)
				 (statement-block-intro . +)
				 (substatement-open . 0)
				 ))))

 (c++-mode . ((indent-tabs-mode . t)
	      (tab-width . 4)
	      (c-basic-offset . 4)
	      (c-file-offsets . ((block-open . 0)
				 (statement-block-intro . +)
				 (substatement-open . 0)
				 )))))
