NAME=standalone
TYPE=application

LBITS := $(shell getconf LONG_BIT)

MODE_SOURCES= \
	lextable.cpp mode_standalone.cpp

MODE_DEFINES=\
	MODE_STANDALONE
	
MODE_LDFLAGS=\
	-Wl,--script=standalone.link

MODE_CCFLAGS=\
	-m$(LBITS)

include Makefile.common
