NAME=standalone-community
TYPE=application

include ../rules/environment.linux.makefile

MODE_SOURCES= \
	stacksecurity.cpp

MODE_DEPS=libkernel-standalone.a

MODE_LIBS=kernel-standalone

MODE_LDFLAGS_FINAL=--script=standalone-$(ARCH).link

include Makefile.common
