NAME=installer
TYPE=application

MODE_SOURCES= \
	lextable.cpp minizip.cpp mode_installer.cpp mode_installer_lnx.cpp bsdiff_apply.cpp

MODE_DEFINES=\
	MODE_INSTALLER
	
ifeq ($(shell gcc -dumpmachine),x86_64-linux-gnu)
	MODE_LDFLAGS=\
		-Wl,--script=installer-x64.link
else
	MODE_LDFLAGS=\
		-Wl,--script=installer.link
endif

include Makefile.common
