NAME=standalone-community
TYPE=application

LBITS := $(shell getconf LONG_BIT)

MODE_SOURCES= \
	stacksecurity.cpp

MODE_DEPS=libkernel-standalone.a

MODE_LIBS=kernel-standalone

MODE_LDFLAGS=\
	-Wl,--script=standalone.link

MODE_CCFLAGS=\
	-m$(LBITS)

include Makefile.common
