NAME=installer
TYPE=application

MODE_SOURCES= \
	lextable.cpp minizip.cpp mode_installer.cpp mode_installer_lnx.cpp bsdiff_apply.cpp

MODE_DEFINES=\
	MODE_INSTALLER
	
MODE_LDFLAGS=\
	-Wl,--script=installer.link

include Makefile.common
