NAME=engine-community
TYPE=application

MODE_SOURCES= \
	stacksecurity.cpp \
	deploysecurity.cpp \
	startupstack.cpp

MODE_DEPS=libkernel-development.a

MODE_LIBS=kernel-development

startupstack.cpp: src/Environment.rev
	../prebuilt/bin/Revolution.lnx "./compress_data.rev"  "./src/Environment.rev" "./src/startupstack.cpp" "MCstartupstack"

include Makefile.common
