NAME=installer
TYPE=application

include ../rules/environment.linux.makefile

MODE_SOURCES= \
	lextable.cpp minizip.cpp mode_installer.cpp mode_installer_lnx.cpp bsdiff_apply.cpp

MODE_DEFINES=\
	MODE_INSTALLER

MODE_LDFLAGS_FINAL=--script=installer-$(ARCH).link

include Makefile.common
