CUSTOM_DEFINES=\
	LINUX \
	X11 TARGET_PLATFORM_LINUX TARGET_PLATFORM_POSIX \
	GTKTHEME \
	HAVE___THREAD \
	$(KERNEL_DEFINES)

CUSTOM_INCLUDES=\
	./src \
	$(KERNEL_INCLUDES)

CUSTOM_CCFLAGS=\
	-Wall -Wno-unused-variable -Wno-switch -Wno-non-virtual-dtor -fno-exceptions -fno-rtti \
	-fmessage-length=0 \
	$(KERNEL_CCFLAGS)

ifeq ($(ARCH),i386)
	CUSTOM_CCFLAGS:=$(CUSTOM_CCFLAGS) -march=i486
endif

include ../rules/mlc.linux.makefile

include ../rules/archive.linux.makefile
