NAME=libcore
TYPE=archive

include ../rules/environment.linux.makefile

SOURCES=core.cpp module.cpp thread.cpp filesystem.cpp

CUSTOM_DEFINES=

CUSTOM_INCLUDES=./src

CUSTOM_CCFLAGS=-fno-exceptions -fno-rtti


include ../rules/archive.linux.makefile
