NAME=libcore
TYPE=archive

SOURCES=core.cpp binary.cpp sserialize.cpp sserialize_lnx.cpp module.cpp thread.cpp filesystem.cpp

CUSTOM_DEFINES=

CUSTOM_INCLUDES=./src

CUSTOM_CCFLAGS=-fno-exceptions -fno-rtti


include ../rules/archive.linux.makefile
