NAME=libgif
TYPE=archive

include ../../rules/environment.linux.makefile

SOURCES=\
	dgif_lib.c egif_lib.c gif_err.c gif_font.c gif_hash.c gifalloc.c quantize.c

CUSTOM_DEFINES=

CUSTOM_INCLUDES=./src

CUSTOM_CCFLAGS=

include ../../rules/archive.linux.makefile
