NAME=libz
TYPE=archive

include ../../rules/environment.linux.makefile

SOURCES=adler32.c compress.c crc32.c deflate.c gzio.c infback.c inffast.c inflate.c \
	inftrees.c trees.c uncompr.c zutil.c

CUSTOM_DEFINES=

CUSTOM_INCLUDES=./src

CUSTOM_CCFLAGS=

include ../../rules/archive.linux.makefile
