NAME=server-revzip
TYPE=library

include ../rules/environment.linux.makefile

SOURCES=revzip.cpp

CUSTOM_DEFINES=

CUSTOM_INCLUDES=./src

CUSTOM_LIBS=zip external z
CUSTOM_DYNAMIC_LIBS=

CUSTOM_CCFLAGS=

CUSTOM_LDFLAGS=

include ../rules/library.linux.makefile
