NAME=libcairopdf
TYPE=archive

include ../../rules/environment.linux.makefile

SOURCES=cairo-analysis-surface.c cairo-arc.c cairo-array.c cairo-atomic.c \
	cairo-base64-stream.c cairo-base85-stream.c \
	cairo-bentley-ottmann-rectangular.c cairo-bentley-ottmann-rectilinear.c \
	cairo-bentley-ottmann.c cairo-cache.c cairo-cff-subset.c cairo-clip.c \
	cairo-color.c cairo-debug.c cairo-deflate-stream.c \
	cairo-font-face-twin-data.c cairo-font-face-twin.c cairo-font-face.c \
	cairo-font-options.c cairo-freelist.c cairo-gstate.c cairo-hash.c \
	cairo-hull.c cairo-image-info.c cairo-image-surface.c cairo-matrix.c \
	cairo-meta-surface.c cairo-misc.c cairo-mutex.c cairo-output-stream.c \
	cairo-paginated-surface.c cairo-path-bounds.c cairo-path-fill.c \
	cairo-path-fixed.c cairo-path-in-fill.c cairo-path-stroke.c cairo-path.c \
	cairo-pattern.c cairo-pdf-operators.c cairo-pdf-surface.c cairo-pdf-ext.c \
	cairo-pen.c cairo-polygon.c cairo-rectangle.c \
	cairo-region.c cairo-scaled-font-subsets.c cairo-scaled-font.c cairo-slope.c \
	cairo-spans.c cairo-spline.c cairo-stroke-style.c cairo-surface-clipper.c \
	cairo-surface-fallback.c cairo-surface-wrapper.c cairo-surface.c \
	cairo-tee-surface.c cairo-tor-scan-converter.c cairo-toy-font-face.c \
	cairo-traps.c cairo-truetype-subset.c cairo-type1-fallback.c \
	cairo-type3-glyph-surface.c cairo-unicode.c cairo-user-font.c cairo-version.c \
	cairo-wideint.c cairo.c cairo-ft-font.c cairo-type1-subset.c \
	pixman-access-accessors.c pixman-access.c pixman-bits-image.c \
	pixman-combine32.c pixman-combine64.c pixman-cpu.c pixman-edge-accessors.c \
	pixman-edge.c pixman-fast-path.c pixman-general.c pixman-gradient-walker.c \
	pixman-image.c pixman-implementation.c pixman-linear-gradient.c pixman-matrix.c \
	pixman-radial-gradient.c pixman-region16.c pixman-region32.c pixman-solid-fill.c \
	pixman-trap.c pixman-utils.c pixman.c

CUSTOM_DEFINES=

CUSTOM_INCLUDES=./src

CUSTOM_CCFLAGS=

include ../../rules/archive.linux.makefile
