#                                                                 -*-Makefile-*-

NAME ?= libstdscript

# Add source code derived from MLC to list of source files
SOURCES += $(MLC_BUILT_SOURCES)

include ../rules/environment.linux.makefile

include ../rules/mlc.linux.makefile

# Inherit almost all settings from libscript
include Makefile.libscript
