all: libscript libstdscript
clean: libstdscript-clean

libscript:
	$(MAKE) -f Makefile.libscript libscript

libstdscript:
	$(MAKE) -f Makefile.libstdscript libstdscript

.PHONY: all clean
.PHONY: libscript
.PHONY: libstdscript libstdscript-clean
