NAME=server-revxml
TYPE=library

include ../rules/environment.linux.makefile

SOURCES=revxml.cpp xmlattribute.cpp xmldoc.cpp xmlelement.cpp

CUSTOM_DEFINES=

CUSTOM_INCLUDES=./src ../libxml/include ../libxslt/include

CUSTOM_LIBS=external xml xslt z
CUSTOM_DYNAMIC_LIBS=m

CUSTOM_CCFLAGS=

CUSTOM_LDFLAGS=

include ../rules/library.linux.makefile
