NAME=server-revxml
TYPE=library

include ../rules/environment.linux.makefile

SOURCES=revxml.cpp xmlattribute.cpp xmldoc.cpp xmlelement.cpp

CUSTOM_DEFINES=LIBXML_XPATH_ENABLED

CUSTOM_INCLUDES=./src ../libxml/include

CUSTOM_LIBS=external xml z
CUSTOM_DYNAMIC_LIBS=m

CUSTOM_CCFLAGS=

CUSTOM_LDFLAGS=

include ../rules/library.linux.makefile
