NAME=revxml
TYPE=library

include ../rules/environment.linux.makefile

SOURCES=revxml.cpp xmlattribute.cpp xmldoc.cpp xmlelement.cpp

CUSTOM_DEFINES=

CUSTOM_INCLUDES=./src

CUSTOM_LIBS=xml xslt external z

CUSTOM_CCFLAGS=

CUSTOM_LDFLAGS=

CUSTOM_DYNAMIC_LIBS=m

include ../rules/library.linux.makefile
