NAME=server-revxml
TYPE=library

SOURCES=revxml.cpp xmlattribute.cpp xmldoc.cpp xmlelement.cpp

CUSTOM_DEFINES=

CUSTOM_INCLUDES=./src ../libxml/include

CUSTOM_LIBS=external xml z
CUSTOM_DYNAMIC_LIBS=

CUSTOM_CCFLAGS=

CUSTOM_LDFLAGS=

include ../rules/library.linux.makefile
