NAME=libexternalv1
TYPE=archive

include ../rules/environment.linux.makefile

SOURCES=external.c

CUSTOM_DEFINES=

CUSTOM_INCLUDES=./src ./include

CUSTOM_CCFLAGS=

include ../rules/archive.linux.makefile
