NAME=libpng
TYPE=archive

include ../../rules/environment.linux.makefile

SOURCES=\
	png.c pngerror.c pnggccrd.c pngget.c pngmem.c pngpread.c pngread.c \
	pngrio.c pngrtran.c pngrutil.c pngset.c pngtrans.c pngvcrd.c pngwio.c \
	pngwrite.c pngwtran.c pngwutil.c

CUSTOM_DEFINES=

CUSTOM_INCLUDES=./src

CUSTOM_CCFLAGS=

include ../../rules/archive.linux.makefile
