NAME=revandroid
TYPE=library

include ../rules/environment.linux.makefile

SOURCES=revandroid.cpp

CUSTOM_DEFINES=

CUSTOM_INCLUDES=./src ../libexternalv1/include

CUSTOM_LIBS=externalv1
CUSTOM_DYNAMIC_LIBS=pthread

CUSTOM_CCFLAGS=

CUSTOM_LDFLAGS=

include ../rules/library.linux.makefile
