NAME=revandroid
TYPE=library

SOURCES=revandroid.cpp

CUSTOM_DEFINES=

CUSTOM_INCLUDES=./src ../libexternalv1/include

CUSTOM_LIBS=externalv1

CUSTOM_STATIC_LIBS=stdc++

CUSTOM_DYNAMIC_LIBS=pthread

CUSTOM_CCFLAGS=

CUSTOM_LDFLAGS=

include ../rules/library.linux.makefile
