NAME=libexternal
TYPE=archive

include ../rules/environment.linux.makefile

SOURCES=external.c unxsupport.cpp

CUSTOM_DEFINES=

CUSTOM_INCLUDES=./src

CUSTOM_CCFLAGS=

include ../rules/archive.linux.makefile
