const char *MCexecutionerrors =
	"Handler: Running low on memory, script aborted\n"
	"recursionLimit: Recursion limit reached\n"
	"abs: error in source expression\n"
	"accept: bad expression\n"
	"aclip: playLoudness is not an integer\n"
	"acos: error in source expression\n"
	"acos: domain error\n"
	"add: error in matrix operation\n"
	"add: destination has a bad format (numeric?)\n"
	"add: error in source expression\n"
	"add: can't set destination\n"
	"add: can't add array to scalar\n"
	"aliasReference: error in file expression\n"
	"Operators and: error in left operand\n"
	"Operators and: error in right operand\n"
	"Operators bitAnd: error in left operand\n"
	"Operators bitAnd: error in right operand\n"
	"annuity: error in period expression\n"
	"annuity: error in rate expression\n"
	"answer: error in question expression\n"
	"answer: error in response expression\n"
	"answer: error in title expression\n"
	"split: error in expression\n"
	"arrowKey: error in direction expression\n"
	"arrowKey: not a direction\n"
	"asin: error in source expression\n"
	"asin: domain error\n"
	"ask: error in question expression\n"
	"ask: error in reply expression\n"
	"ask: error in title expression\n"
	"atan2: error in first expression\n"
	"atan2: error in second expression\n"
	"atan2: domain error\n"
	"atan: error in source expression\n"
	"atan: domain error\n"
	"average: error in source expression\n"
	"base64Decode: error in source expression\n"
	"base64Encode: error in source expression\n"
	"baseConvert: bad destination base\n"
	"baseConvert: error in source expression\n"
	"baseConvert: bad source base\n"
	"baseConvert: can't convert this number\n"
	"baseConvert: destination is not base 10\n"
	"beep: error in expression\n"
	"binaryDecode: destination is not a variable\n"
	"binaryDecode: invalid data for parameter\n"
	"binaryDecode: not enough parameters\n"
	"binaryDecode: error in source expression\n"
	"binaryEncode: invalid data for parameter\n"
	"binaryEncode: not enough parameters\n"
	"binaryEncode: error in source expression\n"
	"Button: bad accelerator modifier\n"
	"Button: family is not an integer\n"
	"Button: menuButton is not an integer\n"
	"Button: menuHistory is not an integer\n"
	"Button: menuLines is not an integer\n"
	"Button: mnemonic is not an integer\n"
	"cancel: message id is not an integer\n"
	"charToNum: error in source expression\n"
	"choose: error in expression\n"
	"choose: not a tool\n"
	"Chunk: error in background expression\n"
	"Chunk: error in card expression\n"
	"Chunk: error in character range\n"
	"Chunk: container is not a button or field\n"
	"Chunk: error in chunk expression\n"
	"Chunk: error in item range\n"
	"Chunk: error in line range\n"
	"Chunk: error in object expression\n"
	"Chunk: error in range end expression\n"
	"Chunk: error in range start expression\n"
	"Chunk: error in stack expression\n"
	"Chunk: error in text string\n"
	"Chunk: can't separate tokens\n"
	"Chunk: can't separate words\n"
	"Chunk: can't delete object\n"
	"Chunk: can't find object\n"
	"Chunk: can't get object attributes\n"
	"Chunk: can't get value of destination container\n"
	"Chunk: can't get number\n"
	"Chunk: can't get source string\n"
	"Chunk: can't get substring\n"
	"Chunk: can't find substring\n"
	"Chunk: can't set attributes\n"
	"Chunk: can't store to destination container\n"
	"Chunk: can't set as a number\n"
	"Chunk: can't find background\n"
	"Chunk: can't find card\n"
	"Chunk: no such object\n"
	"Chunk: can't set property\n"
	"Chunk: can't find stack\n"
	"Chunk: no target found\n"
	"Chunk: can't select object that isn't open\n"
	"Chunk: source is not a container\n"
	"Chunk: can't find object to store into\n"
	"Chunk: can't get source from container\n"
	"Chunk: destination is not a container\n"
	"click: script aborted\n"
	"click: expression is not a button number\n"
	"click: error in point expression\n"
	"click: expression is not a point\n"
	"click: stack is not open\n"
	"clone: error in name expression\n"
	"clone: can't clone this object\n"
	"clone: stack is locked\n"
	"clone: can't find object to clone\n"
	"close: error in name expression\n"
	"close: can't find stack\n"
	"color: error setting selectedColor\n"
	"compact: can't find stack to save\n"
	"compact: object is not a stack\n"
	"compound: error in periods expression\n"
	"compound: error in rate expression\n"
	"compress: error in source expression\n"
	"compress: error occurred during compression\n"
	"Operators &&: error in left operand\n"
	"Operators &&: error in right operand\n"
	"Operators &: error in left operand\n"
	"Operators &: error in right operand\n"
	"Operators contains: error in left operand\n"
	"Operators contains: error in right operand\n"
	"convert: can't read from container\n"
	"convert: can't set container\n"
	"copy: invalid destination object\n"
	"copy: can't find destination object\n"
	"copy: can't copy source object\n"
	"copy: can't find source object\n"
	"copy: stack is password protected\n"
	"cos: error in source expression\n"
	"cos: domain error\n"
	"create: error in bad parent or background expression\n"
	"create: error in name expression\n"
	"create: error in file name expression\n"
	"create: stack is locked (cantModify)\n"
	"crop: error in image expression\n"
	"crop: object is not an image\n"
	"crop: error in rectangle expression\n"
	"crop: expression is not a rectangle\n"
	"cut: can't find or copy object\n"
	"decompress: error in source expression\n"
	"decompress: string is not compressed data\n"
	"decompress: error during decompression\n"
	"delete: error in file or url name expression\n"
	"delete: can't find object\n"
	"disable: can't find object\n"
	"Stack: stack has not been given a file name\n"
	"divide: error in matrix operation\n"
	"divide: destination has a bad format (numeric?)\n"
	"divide: error in source expression\n"
	"divide: can't set destination\n"
	"divide: can't divide scalar by array\n"
	"divide: range error (overflow)\n"
	"divide: divide by zero\n"
	"Operators div: error in matrix operation\n"
	"Operators div: error in left operand\n"
	"Operators div: error in right operand\n"
	"Operators div: can't divide scalar by matrix\n"
	"Operators div: range error (overflow)\n"
	"Operators div: divide by zero\n"
	"do: aborted\n"
	"do: error in source expression\n"
	"do: error in statement\n"
	"do: error in expression\n"
	"do: error in language expression\n"
	"do: unexpected end of line in source expression\n"
	"do: can't find command\n"
	"do: not a command\n"
	"do: license limit exceeded\n"
	"doMenu: error in expression\n"
	"doMenu: don't know this menu item\n"
	"drag: script aborted\n"
	"drag: bad \"button\" number\n"
	"drag: bad end point expression\n"
	"drag: end point is not a point\n"
	"drag: bad start point expression\n"
	"drag: start point is not a point\n"
	"driverNames: error in type expression\n"
	"drives: error in type expression\n"
	"edit: can't find object\n"
	"encrypt: error in source expression\n"
	"Operators =: error in operand\n"
	"exp10: error in source expression\n"
	"exp10: domain error\n"
	"exp1: error in source expression\n"
	"exp1: domain error\n"
	"exp2: error in source expression\n"
	"exp2: domain error\n"
	"export: error in file (or mask file) name expression\n"
	"export: can't open file (or mask file)\n"
	"export: can't write to file, mask file, or container\n"
	"export: no image selected, or image not open\n"
	"export: selected object is not an image\n"
	"Expression: error in numeric factor\n"
	"Expression: error in string factor\n"
	"exp: error in source expression\n"
	"exp: domain error\n"
	"extents: error in variable expression\n"
	"Factor: error in left operand\n"
	"Factor: error in right operand\n"
	"Field: bad text attributes\n"
	"Field: hilitedLine is not an integer\n"
	"Field: scrollbarWidth is not an integer\n"
	"Field: shift is not an integer\n"
	"Field: tabstops is not a positive integer\n"
	"files: no permission to list files or directories\n"
	"filter: bad source string\n"
	"filter: bad pattern string\n"
	"filter: can't set destination\n"
	"find: bad source string\n"
	"flip: can't find image\n"
	"flip: object is not an image\n"
	"flushEvents: bad event type\n"
	"focus: not a valid control\n"
	"fontNames: error in type expression\n"
	"fontSizes: bad font name\n"
	"fontStyles: bad font name\n"
	"fontStyles: bad font size\n"
	"format: bad format string or parameter mismatch\n"
	"Function: error in function handler\n"
	"Function: error in source expression\n"
	"Function: source is not a number\n"
	"Function: is not a number\n"
	"get: error in expression\n"
	"get: can't set destination\n"
	"globalLoc: coordinate is not a point\n"
	"go: error in background expression\n"
	"go: error in card expression\n"
	"go: error in stack expression\n"
	"go: error in window expression\n"
	"go: can't attach menu to this object type\n"
	"go: can't find destination\n"
	"grab: can't find object\n"
	"graphic: not an integer\n"
	"Operators >=: error in operands\n"
	"Operators >: error in operands\n"
	"Group: backSize is not a point\n"
	"Group: hilitedButton is not an integer\n"
	"Group: bad object type\n"
	"Operators (): error in right operand\n"
	"Handler: aborted\n"
	"Handler: error in statement\n"
	"Handler: error in parameter expression\n"
	"Handler: not a valid parameter index\n"
	"hasMemory: bad amount expression\n"
	"hide: error in visual effect expression\n"
	"hide: can't find object\n"
	"hostAddress: error in socket expression\n"
	"hostAddressToName: error in address expression\n"
	"hostName: error in name expression\n"
	"hostNameToAddress: error in name expression\n"
	"if-then: aborted\n"
	"if-then: error in condition expression\n"
	"if-then: error in statement\n"
	"Image: bad pixmap id\n"
	"Image: hotspot is not an integer\n"
	"Image: id is not an integer\n"
	"Image: id is already in use by another object\n"
	"Image: image must be open to set id\n"
	"Image: hotSpot x is not an integer\n"
	"Image: hotSpot y is not an integer\n"
	"import: error in expression\n"
	"import: can't open file, mask file or display\n"
	"import: can't read file, mask file or display\n"
	"import: destination stack is locked (cantModify)\n"
	"insert: can't find object\n"
	"insert: license limit exceeded\n"
	"intersect: two objects required\n"
	"Operators is: error in left operand\n"
	"Operators is: error in right operand\n"
	"Operators is: can't compare operands\n"
	"Operators is: left operand of 'within' is not a point\n"
	"Operators is: right operand of 'within' is not a rectangle\n"
	"isNumber: error in source expression\n"
	"isoToMac: error source expression\n"
	"Operators ,: error in left operand\n"
	"Operators ,: error in right operand\n"
	"keys: parameter is not a variable\n"
	"kill: no such process\n"
	"kill: bad number\n"
	"launch: error in application expression\n"
	"length: error in source expression\n"
	"Operators <=: error in operands\n"
	"Operators <: error in operands\n"
	"ln1: error in source expression\n"
	"ln1: domain error\n"
	"ln: error in source expression\n"
	"ln: domain error\n"
	"load: error in url expression\n"
	"load: error in message expression\n"
	"localLoc: coordinate is not a point\n"
	"log10: error in source expression\n"
	"log10: domain error\n"
	"log2: error in source expression\n"
	"log2: domain error\n"
	"longFilePath: error in file expression\n"
	"macToIso: error source expression\n"
	"mark: bad card expression\n"
	"mark: error in find expression\n"
	"matchChunk: can't set destination variable\n"
	"matchChunk: bad or missing parameter\n"
	"matchChunk: error in pattern expression\n"
	"matchChunk: error in source expression\n"
	"matrix: range error in matrix operation\n"
	"matrixMultiply: error in source expression\n"
	"matrixMultiply: can't multiply these arrays\n"
	"max: error in source expression\n"
	"MCISendString: error in source expression\n"
	"MD5digest: error in source expression\n"
	"median: error in source expression\n"
	"merge: error in source expression\n"
	"Operators -: can't subtract array from scalar\n"
	"Operators -: error in left operand\n"
	"Operators -: error in right operand\n"
	"Operators -: range error (overflow) in array operation\n"
	"Operators -: range error (overflow)\n"
	"min: error in source expression\n"
	"Operators mod: error in matrix operation\n"
	"Operators mod: error in left operand\n"
	"Operators mod: error in right operand\n"
	"Operators mod: can't divide scalar by matrix\n"
	"Operators mod: range error (overflow)\n"
	"Operators mod: divide by zero\n"
	"mouse: error in source expression\n"
	"move: script aborted\n"
	"move: can't find object\n"
	"move: bad end point expression\n"
	"move: bad duration expression\n"
	"move: duration is not a number\n"
	"move: end point is not a point\n"
	"move: bad start point expression\n"
	"move: start point is not a point\n"
	"multiply: error in matrix operation\n"
	"multiply: destination has a bad format (numeric?)\n"
	"multiply: error in source expression\n"
	"multiply: can't set destination\n"
	"multiply: can't multiply scalar by array\n"
	"multiply: range error (overflow)\n"
	"Operators <>: error in operands\n"
	"Operators not: error in right operand\n"
	"Operators bitNot: error in right operand\n"
	"numToChar: error in source expression\n"
	"Object: bad textAlign expression\n"
	"Object: unknown color\n"
	"Object: error in colors\n"
	"Object: can't set layer (card not open, or control in group)\n"
	"Object: not a textStyle\n"
	"Object: stack locked, or object's script is executing\n"
	"Object: object does not have this property\n"
	"Object: height is not an integer\n"
	"Object: layer is not an integer\n"
	"Object: margin is not an integer\n"
	"Object: value is not a boolean (true or false)\n"
	"Object Name:\n"
	"Object: property is not an integer\n"
	"Object: coordinate is not a point\n"
	"Object: rectangle does not have 4 points\n"
	"Object: no Home stack\n"
	"Object: pixel value is not an integer\n"
	"Object: pixmap is not an integer\n"
	"Object: can't set script while it is executing\n"
	"Object: can't set this property\n"
	"Object: textheight is not an integer\n"
	"Object: textsize is not an integer\n"
	"offset: error in start offset expression\n"
	"offset: error in part expression\n"
	"offset: error in whole expression\n"
	"open: error in message expression\n"
	"open: error in name expression\n"
	"open: no permission to open files or processes\n"
	"Operators or: error in left operand\n"
	"Operators or: error in right operand\n"
	"Operators bitOr: error in left operand\n"
	"Operators bitOr: error in right operand\n"
	"Operators /: error in matrix operation\n"
	"Operators /: error in left operand\n"
	"Operators /: error in right operand\n"
	"Operators /: can't divide scalar by matrix\n"
	"Operators /: range error (overflow)\n"
	"Operators /: divide by zero\n"
	"param: error in expression\n"
	"param: bad parameter index\n"
	"param: error in source expression\n"
	"param: is not a number\n"
	"paste: stack is locked (cantModify)\n"
	"peerAddress: error in socket expression\n"
	"place: group is not in this stack or is already on this card\n"
	"place: can't find group\n"
	"place: can't find card\n"
	"place: source is not a group, or cannot be used as a background\n"
	"place: destination is not a card\n"
	"play: can't get sound or movie name\n"
	"play: bad movie location\n"
	"play: bad movie options\n"
	"Operators +: error in left operand\n"
	"Operators +: error in right operand\n"
	"Operators +: range error (overflow)\n"
	"pop: can't set destination\n"
	"post: can't get source\n"
	"post: can't get destination\n"
	"pow: error in left operand\n"
	"pow: error in right operand\n"
	"pow: range error (overflow)\n"
	"print: can't get 'from' or 'to' coordinates\n"
	"print: can't get number of cards\n"
	"print: can't get rectangle\n"
	"print: error printing\n"
	"print: error writing file (disk full?)\n"
	"print: coordinate not a point\n"
	"print: expression is not a rectangle\n"
	"print: not a card\n"
	"print: card or stack must be open to print it\n"
	"print: no card specified\n"
	"arcAngle: not an integer\n"
	"blinkRate: not a number\n"
	"penColor: bad color\n"
	"colormap: bad color name or value\n"
	"Object: error counting objects as number\n"
	"Object: error counting objects as text\n"
	"dragSpeed: not a number\n"
	"effectRate: not a number\n"
	"extendKey: not a number\n"
	"Property: bad array expression\n"
	"gridSize: not an integer\n"
	"idleRate: not a number\n"
	"lineSize: not an integer\n"
	"moveSpeed: not a number\n"
	"multiSpace: not a number\n"
	"polySides: not an integer\n"
	"repeatDelay: not a number\n"
	"repeatRate: not a number\n"
	"doubleClickDelta: not an integer\n"
	"doubleClickTime: not a number\n"
	"roundRadius: not an integer\n"
	"slices: not an integer\n"
	"startAngle: not an integer\n"
	"traceDelay: not a number\n"
	"traceStack: not a stack name\n"
	"print: bad property value\n"
	"syncRate: not a number\n"
	"tooltipDelay: not a number\n"
	"typeRate: not a number\n"
	"userLevel: not an integer\n"
	"beep: not an integer\n"
	"brush: not an integer\n"
	"brush: can't find image\n"
	"brushPattern: not a valid image id\n"
	"brushPattern: can't find image\n"
	"Object: no object to set property\n"
	"Object: can't set object property\n"
	"cursor: not an integer\n"
	"cursor: can't find image\n"
	"Property: value is not a boolean (\"true\" or \"false\")\n"
	"Property: value is not a number\n"
	"defaultStack: can't find stack\n"
	"defaultMenuBar: can't find group\n"
	"Object: does not have this property\n"
	"Object: property is not an integer\n"
	"penPattern: not a valid image id\n"
	"penPattern: can't find image\n"
	"randomSeed: property is not an integer\n"
	"socketTimeout: not a number\n"
	"umask: property is not an integer\n"
	"push: object is not a card\n"
	"push: can't find card\n"
	"put: error in expression\n"
	"put: can't set destination\n"
	"put: can't put into destination\n"
	"queryRegistry: error in source expression\n"
	"random: error in source expression\n"
	"read: aborted\n"
	"read: error in 'at' expression\n"
	"read: error in condition expression\n"
	"read: error in count expression\n"
	"read: error reading\n"
	"read: count is not an integer\n"
	"read: error in 'until' expression\n"
	"read: file is not open\n"
	"read: error in 'for' expression\n"
	"read: process is not open\n"
	"record: error in file expression\n"
	"recordCompression: type must be 4 characters\n"
	"recordInput: type must be 4 characters\n"
	"remove: can't find object\n"
	"remove: object is not a group\n"
	"remove: object is not a card\n"
	"rename: error in source expression\n"
	"rename: error in destination expression\n"
	"repeat: aborted\n"
	"repeat: error in 'for' condition expression\n"
	"repeat: error in statement\n"
	"repeat: error in 'until' condition expression\n"
	"repeat: error in 'while' condition expression\n"
	"repeat: error in 'with' end condition expression\n"
	"repeat: error in 'with' start condition expression\n"
	"repeat: error in 'with' step condition expression\n"
	"repeat: error setting 'with' variable\n"
	"replace: can't set container\n"
	"replace: error in pattern expression\n"
	"replace: error in replacement expression\n"
	"replace: error in container expression\n"
	"replaceText: bad parameter\n"
	"replaceText: bad source string\n"
	"reply: error in keyword expression\n"
	"reply: error in message expression\n"
	"request: error in keyword expression\n"
	"request: error in message expression\n"
	"request: error in program expression\n"
	"request: no permission to request that\n"
	"getResources: error in expression\n"
	"getResources: no permission to get that\n"
	"return: error in expression\n"
	"revert: can't revert Home stack\n"
	"rotate: error in object expression\n"
	"rotate: object is not an editable image\n"
	"rotate: error in angle expression\n"
	"round: error in source or digit expression\n"
	"save: error in file name expression\n"
	"save: saving disabled\n"
	"save: can't find stack to save\n"
	"save: object is not a stack\n"
	"seek: error in file name expression\n"
	"seek: error in offset expression\n"
	"seek: file is not open\n"
	"select: can't select target\n"
	"selectedChunk: error in button or field expression\n"
	"selectedButton: bad family expression\n"
	"selectedButton: bad parent object expression\n"
	"send: error in message handler execution\n"
	"send: error in message expression\n"
	"send: error in 'in' expression\n"
	"send: error in program expression\n"
	"send: bad target expression\n"
	"send: no permission to send that\n"
	"set: error in source expression\n"
	"set: can't set property\n"
	"setRegistry: no permission to get or set registry\n"
	"setRegistry: error in source expression\n"
	"shell: aborted\n"
	"shell: can't run shell command\n"
	"shell: error in source expression\n"
	"shell: no permission to run commands\n"
	"shortFilePath: error in file expression\n"
	"show: error in visual effect expression\n"
	"show: error in location expression\n"
	"show: error in number of cards expression\n"
	"show: location is not in proper x,y form\n"
	"show: can't find object\n"
	"sin: error in source expression\n"
	"sin: domain error\n"
	"sort: can't find object to sort\n"
	"sort: error sorting\n"
	"sort: can't find field\n"
	"specialFolderPath: error in type expression\n"
	"sqrt: error in source expression\n"
	"sqrt: domain error\n"
	"Stack: bad decoration\n"
	"Stack: invalid id (must be greater than current id)\n"
	"Stack: invalid key\n"
	"Stack: bad substack name\n"
	"Stack: can't set mainStack (has substacks?)\n"
	"Stack: deskIcon is not an integer\n"
	"Stack: userLevel is not an integer\n"
	"Stack: size is not an integer\n"
	"Stack: stack is password protected\n"
	"Stack: can't find mainStack\n"
	"Stack: stack is not a mainStack\n"
	"Stack: error in external function handler\n"
	"start: can't find object\n"
	"start: stack is locked\n"
	"start: expression is not a group\n"
	"start: license limit exceeded\n"
	"Handler: error in source expression\n"
	"Handler: can't find handler\n"
	"stdDev: error in expression\n"
	"stop: error in expression\n"
	"stop: target is not a group\n"
	"subtract: error in matrix operation\n"
	"subtract: destination has a bad format (numeric?)\n"
	"subtract: error in source expression\n"
	"subtract: can't set destination\n"
	"subtract: can't subtract array from scalar\n"
	"subwindow: error in expression\n"
	"subwindow: can't find stack or button\n"
	"sum: error in source expression\n"
	"switch: error in condition expression\n"
	"switch: error in case expression\n"
	"switch: error in statement\n"
	"textHeightSum: can't find object\n"
	"tan: error in source expression\n"
	"tan: domain error\n"
	"there: error in source expression\n"
	"throw: error in source expression\n"
	"Operators *: error in matrix operation\n"
	"Operators *: error in left operand\n"
	"Operators *: error in right operand\n"
	"Operators *: range error (overflow)\n"
	"toLower: error in source expression\n"
	"topStack: error in source expression\n"
	"toUpper: error in source expression\n"
	"transpose: source is not a variable\n"
	"transpose: can't transpose this array\n"
	"trunc: error in source expression\n"
	"try: error in statement\n"
	"type: script aborted\n"
	"type: bad string expression\n"
	"ungroup: can't find group\n"
	"ungroup: target is not a group\n"
	"uniDecode: error in language expression\n"
	"uniDecode: error in source expression\n"
	"uniEncode: error in language expression\n"
	"uniEncode: error in source expression\n"
	"unload: error in url expression\n"
	"unlock: expression is not a visual effect\n"
	"urlDecode: error in source expression\n"
	"urlEncode: error in source expression\n"
	"urlStatus: error in url expression\n"
	"value: error in source expression\n"
	"value: error executing expression\n"
	"value: can't find object\n"
	"Array: bad index expression\n"
	"Chunk: source is not a character\n"
	"Chunk: source is not a number\n"
	"visual: bad effect expression\n"
	"wait: aborted\n"
	"wait: error in expression\n"
	"wait: expression is not a number\n"
	"within: can't find control\n"
	"within: not a point\n"
	"write: error in expression\n"
	"Operators bitXor: error in left operand\n"
	"Operators bitXor: error in right operand\n"
	"Property stackFileVersion: not a valid version\n"
	"Property stackFileVersion: version not supported\n"
	"External handler: exception\n"
	"export: Empty rectangle\n"
	"import: Empty rectangle\n"
	"Property dragAction: Unknown action\n"
	"Property dragImageOffset: Not a point\n"
	"Property dragDelta: Not a number\n"
	"clipboard: invalid mix of data types\n"
	"clipboard: invalid text\n"
	"wrap: bad array\n"
	"wrap: illegal type for left operand\n"
	"wrap: illegal type for right operand\n"
	"wrap: type mismatch\n"
	"wrap: overflow\n"
	"wrap: division by zero\n"
	"begins/ends with: illegal type for right operand\n"
	"begins/ends with: illegal type for left operand\n"
	"load extension: bad filename\n"
	"UNUSED\n"
	"UNUSED\n"
	"UNUSED\n"
	"UNUSED\n"
	"UNUSED\n"
	"UNUSED\n"
	"UNUSED\n"
	"graphic: not a boolean\n"
	"graphic: bad fill rule\n"
	"graphic: bad gradient type\n"
	"graphic: bad gradient ramp\n"
	"graphic: bad gradient point\n"
	"graphic: bad gradient quality\n"
	"graphic: bad gradient key\n"
	"graphic: bad cap style\n"
	"graphic: bad join style\n"
	"byteToNum: bad expression\n"
	"numToByte: bad expression\n"
	"arrayEncode: bad expression\n"
	"arrayEncode: failure\n"
	"arrayDecode: bad expression\n"
	"arrayDecode: failure\n"
	"parentScript: bad object\n"
	"dispatch: bad message\n"
	"dispatch: bad command\n"
	"dispatch: bad target\n"
	"queryRegistry: bad destination\n"
	"parentScript: loop in hierarchy\n"
	"Security: disk access not allowed\n"
	"Security: network access not allowed\n"
	"Security: external command access not allowed\n"
	"Security: registry access not allowed\n"
	"<not used>\n"
	"Security: printer access not allowed\n"
	"Security: audio and camera access not allowed\n"
	"\n"
	"\n"
	"\n"
	"\n"
	"\n"
	"\n"
	"\n"
	"\n"
	"\n"
	"\n"
	"Security: AppleScript access not allowed\n"
	"Security: alternate script execution not allowed\n"
	"processType: bad value\n"
	"processType: cannot change\n"
	"\n"
	"\n"
	"do in browser: not supported\n"
	"do in browser: failed\n"
	"editMode: Bad value\n"
	"export: Bad palette\n"
	"export: Invalid palette size\n"
	"printing: Bad options array\n"
	"\n"
	"printing: Unknown destination\n"
	"object: cannot change id while in group edit mode\n"
	"print: bad anchor name\n"
	"print: bad anchor location\n"
	"print: anchor location not a point\n"
	"print: bad link destination\n"
	"print: bad link area\n"
	"print: link area not a rectangle\n"
	"randomBytes: bad count\n"
	"sha1Digest: bad source\n"
	"stackLimit: not a number\n"
	"could not load security library\n"
	"group: cannot be background or shared (it is nested)\n"
	"group: must be shared (it is placed on more than one card, or unplaced)\n"
	"group: cannot group background or shared groups\n"
	"print: bad bookmark title\n"
	"print: bad bookmark level\n"
	"print: bad bookmark position\n"
	"print: bad bookmark initial state\n"
	"Script File Index:\n"
	"include: could not find file\n"
	"script: parsing error\n"
	"script: bad statement\n"
	"include: not supported in this environment\n"
	"include: bad filename\n"
	"include: nesting depth limit reached\n"
	"require: not supported in this environment\n"
	"\n"
	"\n"
	"errorMode: bad value\n"
	"outputEncoding: bad value\n"
	"outputLineEnding: bad value\n"
	"Script Error Position:\n"
	"defaultNetworkInterface: network interface must be an IPv4 address\n"
	"layerMode: must be 'static', 'dynamic' or 'scrolling'\n"
	"tileSize: must be a power of two between 16 and 256\n"
	"tileCompositor: unknown type\n"
	"tileCompositor: not supported on this platform\n"
	"intersects: error in threshold expression\n"
	"intersects: threshold must be a non-negative number, \"bounds\", \"pixels\" or \"opaque pixels\"\n"
	"session: not supported in this environment\n"
	"sessionSavePath: bad value\n"
	"sessionLifetime: bad value\n"
	"sessionName: bad value\n"
	"sessionId: bad value\n"
	"lock: bad rect expr\n"
	"lock: not a rectangle\n"
	"field: bad listStyle value\n"
	"field: firstIndent must be an integer\n"
	"field: leftIndent must be an integer\n"
	"field: rightIndent must be an integer\n"
	"field: spaceBefore must be an integer\n"
	"field: spaceAfter must be an integer\n"
	"field: listDepth must be an integer between 1 and 16.\n"
	"field: borderWidth must be an integer\n"
	"field: listIndent must be an integer\n"
	"field: padding must be an integer\n"
	"Chunk: can't store unicode to destination container\n"
	"relayer: target not a container\n"
	"relayer: couldn't resolve target object\n"
	"relayer: couldn't resolve source control\n"
	"relayer: source not a control\n"
	"relayer: source and target not on the same card\n"
	"relayer: layer not an integer\n"
	"relayer: bad layer expression\n"
	"relayer: target not a control\n"
	"relayer: cannot move a control into a descendent\n"
	"relayer: required objects disappeared while processing\n"
	"controlAtLoc: location not a point\n"
	"do: no caller\n"
	"read: invalid command for datagram socket\n"
	"field: listIndex must be an integer\n"
	"image cache limit: not a number\n"
	"controls don't have the same owner\n"
	"uuid: bad type expression\n"
	"uuid: wrong number of arguments for specified type\n"
	"uuid: unsupported type\n"
	"uuid: bad namespace expression\n"
	"uuid: namespace not a uuid\n"
	"uuid: bad name expression\n"
	"uuid: not enough randomness available\n"
;

const char *MCparsingerrors =
	"Object Name:\n"
	"set: license limit exceeded\n"
	"abs: bad parameter\n"
	"accept: bad expression\n"
	"acos: bad parameter\n"
	"add: bad destination\n"
	"add: bad expression\n"
	"add: missing 'to'\n"
	"aliasReference: bad expression\n"
	"annuity: bad parameter\n"
	"answer: bad question\n"
	"answer: bad response\n"
	"answer: bad title\n"
	"split: bad variable\n"
	"split: missing 'with'\n"
	"split: bad expression\n"
	"arrowKey: bad direction expression\n"
	"asin: bad parameter\n"
	"ask: bad question\n"
	"ask: bad reply\n"
	"ask: bad title\n"
	"atan2: bad parameter\n"
	"atan: bad parameter\n"
	"average: bad parameter\n"
	"base64Decode: bad parameter\n"
	"base64Encode: bad parameter\n"
	"baseConvert: bad parameter\n"
	"binaryDecode: bad expression\n"
	"binaryEncode: bad expression\n"
	"cancel: bad message expression\n"
	"charToNum: bad parameter\n"
	"choose: bad expression\n"
	"choose: no tool specified\n"
	"Chunk: token is not a chunk\n"
	"Chunk: bad destination\n"
	"Chunk: bad non-chunk expression\n"
	"Chunk: bad chunk order (must be small to large)\n"
	"Chunk: bad preposition\n"
	"Chunk: bad range\n"
	"Chunk: bad stack reference\n"
	"Chunk: missing chunk\n"
	"Chunk: bad expression\n"
	"Chunk: bad range end expression\n"
	"Chunk: can't create a variable with that name (explicitVariables?)\n"
	"click: bad \"button\" expression\n"
	"click: bad location expression\n"
	"click: missing 'at'\n"
	"clone: bad name expression\n"
	"clone: bad target expression\n"
	"close: bad stack expression\n"
	"close: bad stack name\n"
	"close: no stack type\n"
	"compact: error in stack expression\n"
	"compound: bad parameter\n"
	"compress: bad parameter\n"
	"constant: error in value string\n"
	"constant: missing value string\n"
	"convert: 'and' in the wrong place\n"
	"convert: no container specified\n"
	"convert: no format supplied\n"
	"convert: not a valid format\n"
	"convert: missing 'to'\n"
	"copy: bad destination object expression\n"
	"cos: bad parameter\n"
	"create: bad background or card expression\n"
	"create: error in file name expression\n"
	"create: can't create this type\n"
	"create: not an object type\n"
	"create: no file name supplied\n"
	"create: no alias or directory name supplied\n"
	"create: no object type\n"
	"crop: bad image expression\n"
	"crop: bad rect expression\n"
	"decompress: bad parameter\n"
	"define: bad object expression\n"
	"define: invalid property name\n"
	"delete: bad file expression\n"
	"delete: bad variable expression\n"
	"disable: no control specified\n"
	"divide: bad destination\n"
	"divide: bad expression\n"
	"divide: missing 'by'\n"
	"do: bad expression\n"
	"do: bad language expression\n"
	"doMenu: bad expression\n"
	"drag: bad \"button\" expression\n"
	"drag: bad end location expression\n"
	"drag: bad start location expression\n"
	"drag: missing 'from'\n"
	"drag: missing 'to'\n"
	"driverNames: bad in type expression\n"
	"drives: bad in type expression\n"
	"edit: missing 'of'\n"
	"edit: missing 'script'\n"
	"edit: no object specified\n"
	"encrypt: bad parameter\n"
	"exit: bad destination expression\n"
	"exit: no destination expression\n"
	"exp10: bad parameter\n"
	"exp1: bad parameter\n"
	"exp2: bad parameter\n"
	"export: bad file name\n"
	"export: bad mask file name\n"
	"export: bad image or image type expression\n"
	"export: missing file name or container\n"
	"export: missing 'mask'\n"
	"export: missing 'to'\n"
	"export: no image type specified\n"
	"Expression: bad chunk\n"
	"Expression: bad function\n"
	"Expression: bad property\n"
	"Expression: double binary operator\n"
	"Expression: no binary operator\n"
	"Expression: missing factor\n"
	"Expression: missing left operand to binary operator\n"
	"Expression: missing ')'\n"
	"Expression: bad factor\n"
	"Expression: unquoted literal\n"
	"Expression: missing ')' before factor\n"
	"exp: bad parameter\n"
	"extents: bad parameter\n"
	"Function: bad parameter\n"
	"Function: missing 'of'\n"
	"Function: missing '('\n"
	"Function: missing ')'\n"
	"Function: separator is not a ','\n"
	"filter: bad container\n"
	"filter: bad pattern expression\n"
	"filter: expected \"with\"\n"
	"find: bad field expression\n"
	"find: bad string expression\n"
	"find: no string expression\n"
	"flip: bad image expression\n"
	"flip: missing direction\n"
	"flushEvents: bad event type expression\n"
	"focus: bad object expression\n"
	"fontNames: bad type expression\n"
	"fontSizes: bad font name string\n"
	"fontStyle: bad font name or size expression\n"
	"format: bad format string\n"
	"Function: bad form\n"
	"Function: bad object expression\n"
	"Function: bad parameter\n"
	"Function: can't modify this function\n"
	"Function: missing function or property\n"
	"Function: can't modify this token\n"
	"get: bad expression\n"
	"global: not a valid variable name\n"
	"globalLoc: bad point expression\n"
	"go: bad destination chunk\n"
	"go: bad chunk expression\n"
	"go: bad chunk order (must be small to large)\n"
	"go: bad destination type\n"
	"go: bad destination expression\n"
	"go: bad direct destination\n"
	"go: bad window expression\n"
	"go: preposition in the wrong place\n"
	"go: duplicate chunk\n"
	"go: no destination specified\n"
	"go: missing id\n"
	"go: no window mode specified\n"
	"grab: bad object expression\n"
	"Handler: bad character between handlers\n"
	"Handler: no end of line\n"
	"Handler: error in handler\n"
	"Handler: error in command\n"
	"Handler: end doesn't match handler name\n"
	"Handler: unexpected end of line\n"
	"Handler: bad handler name (may be reserved word)\n"
	"Handler: not a valid parameter name\n"
	"Handler: unexpected end of line in parameters\n"
	"Handler: error in variable or constant declaration\n"
	"Handler: bad command\n"
	"Handler: missing handler name after end\n"
	"Handler: no name specified\n"
	"Handler: not a command\n"
	"hasMemory: bad amount expression\n"
	"hide: error in visual effect expression\n"
	"hide: error in target object expression\n"
	"hostAddress: error in socket expression\n"
	"hostAddressToName: error in address expression\n"
	"hostName: error in name expression\n"
	"hostNameToAddress: error in name expression\n"
	"if: bad condition\n"
	"if: unexpected end of line\n"
	"if: error in command\n"
	"if: garbage where a command should be\n"
	"if: not a command\n"
	"if: missing 'then'\n"
	"if: missing 'end if'\n"
	"import: bad file or display name\n"
	"import: bad mask file name\n"
	"import: bad image type\n"
	"import: missing file or display name\n"
	"import: missing 'from'\n"
	"import: missing 'mask'\n"
	"import: no image type specified\n"
	"insert: bad object specification\n"
	"insert: expected 'into'\n"
	"insert: missing 'script'\n"
	"insert: expected 'front' or 'back'\n"
	"intersect: two objects are required\n"
	"is: bad chunk type\n"
	"is: bad validation type\n"
	"is: missing validation type\n"
	"is: no right operand\n"
	"isNumber: bad expression\n"
	"isoToMac: bad source expression\n"
	"keys: bad variable name\n"
	"kill: bad process name\n"
	"kill: no process\n"
	"launch: error in application expression\n"
	"length: bad parameter\n"
	"ln: bad parameter\n"
	"ln1: bad parameter\n"
	"load: error in url expression\n"
	"load: error in message expression\n"
	"local: error in initialization string\n"
	"local: not a valid variable or constant name\n"
	"local: name shadows another variable or constant\n"
	"localLoc: bad point expression\n"
	"lock: no target object specified\n"
	"lock: not a valid target object\n"
	"log10: bad parameter\n"
	"log2: bad parameter\n"
	"longFilePath: bad file expression\n"
	"macToIso: bad source expression\n"
	"mark: bad 'field' expression\n"
	"mark: bad 'finding' string expression\n"
	"mark: bad 'where' expression\n"
	"mark: missing 'by' or 'where'\n"
	"mark: missing 'cards'\n"
	"mark: missing 'finding'\n"
	"mark: missing 'finding' string\n"
	"mark: expected 'by' or 'where'\n"
	"mark: expected 'cards'\n"
	"matchChunk: bad parameter\n"
	"matrixMultiply: bad parameter\n"
	"max: bad parameter\n"
	"MCISendString: bad source expression\n"
	"MD5digest: bad source expression\n"
	"median: bad source expression\n"
	"me: unexpected 'the'\n"
	"merge: bad source expression\n"
	"min: bad parameter\n"
	"mouse: bad parameter\n"
	"move: bad object expression\n"
	"move: bad end location expression\n"
	"move: bad start location expression\n"
	"move: expected 'messages' or 'waiting'\n"
	"move: missing 'to'\n"
	"multiply: bad destination\n"
	"multiply: bad expression\n"
	"multiply: missing 'by'\n"
	"next: missing 'repeat'\n"
	"next: token is not 'repeat'\n"
	"numToChar: bad parameter\n"
	"offset: bad parameter\n"
	"open: error in message expression\n"
	"open: bad mode\n"
	"open: bad file name\n"
	"open: type must be 'file' or 'process'\n"
	"open: no mode specified\n"
	"open: no type specified\n"
	"param: bad expression\n"
	"param: bad parameter\n"
	"Script: garbage character in script\n"
	"Script: missing '\"' after literal\n"
	"pass: mismatched or missing message to pass\n"
	"pause: bad clip name expression\n"
	"peerAddress: error in socket expression\n"
	"place: bad background expression\n"
	"place: bad card expression\n"
	"play: bad clip name expression\n"
	"play: bad location expression\n"
	"play: bad options expression\n"
	"play: bad tempo expression\n"
	"play: bad stack expression\n"
	"pop: bad card expression\n"
	"pop: preposition in the wrong place\n"
	"pop: no card specified\n"
	"post: bad source expression\n"
	"post: missing 'to'\n"
	"post: bad destination expression\n"
	"print: bad target card\n"
	"print: bad 'from' expression\n"
	"print: bad rectangle expression\n"
	"print: missing 'to'\n"
	"print: bad 'to' expression\n"
	"Properties: bad chunk expression\n"
	"Properties: bad array index expression\n"
	"Properties: can't modify this property\n"
	"Properties: missing 'of'\n"
	"Properties: missing 'of' or 'in'\n"
	"Properties: no such property\n"
	"Properties: token is not a property\n"
	"Properties: expecting 'of'\n"
	"Properties: expecting 'of' or 'in'\n"
	"push: bad expression\n"
	"put: bad chunk\n"
	"put: bad expression\n"
	"put: preposition must be 'before', 'into' or 'after'\n"
	"queryRegistry: bad parameter expression\n"
	"random: bad parameter\n"
	"read: bad 'at' expression\n"
	"read: bad condition\n"
	"read: bad message expression\n"
	"read: bad file name expression\n"
	"read: bad source type (should be 'file' or 'process')\n"
	"read: no termination condition specified\n"
	"read: missing 'from'\n"
	"read: bad termination condition\n"
	"read: missing source type ('file' or 'process')\n"
	"record: missing 'file' or file name\n"
	"remove: bad object expression\n"
	"remove: expected 'from'\n"
	"remove: expected 'front' or 'back'\n"
	"rename: bad expression\n"
	"repeat: error in command\n"
	"repeat: bad termination condition\n"
	"repeat: unexpected end of line in condition\n"
	"repeat: missing condition\n"
	"repeat: unexpected end of line\n"
	"repeat: error in 'for' condition\n"
	"repeat: garbage in repeat condition\n"
	"repeat: not a command\n"
	"repeat: bad 'with' end expression\n"
	"repeat: bad 'with' start expression\n"
	"repeat: bad 'with' step expression\n"
	"repeat: bad 'with' variable\n"
	"repeat: missing 'to' after 'down'\n"
	"repeat: missing '='\n"
	"repeat: missing 'in'\n"
	"repeat: garbage where a command should be\n"
	"repeat: expecting '='\n"
	"repeat: expecting 'to'\n"
	"repeat: missing 'to'\n"
	"repeat: missing 'with' variable\n"
	"repeat: missing 'end repeat'\n"
	"replace: bad container expression\n"
	"replace: bad expression\n"
	"replaceText: bad parameter\n"
	"reply: error in message expression\n"
	"reply: error in keyword expression\n"
	"request: error in message expression\n"
	"request: error in program expression\n"
	"request: no 'type' expression\n"
	"request: type must be class, ID, sender, returnID, or data\n"
	"reset: missing 'paint', 'cursors', or template object\n"
	"getResources: bad parameter\n"
	"return: error in expression\n"
	"rotate: error in image expression\n"
	"rotate: error in angle expression\n"
	"round: bad parameter\n"
	"save: error in stack expression\n"
	"save: error in file name expression\n"
	"seek: bad mode (should be 'to' or 'relative')\n"
	"seek: bad file name expression\n"
	"seek: expected 'file'\n"
	"seek: bad offset expression\n"
	"seek: missing 'in'\n"
	"seek: no mode ('to' or 'relative')\n"
	"seek: missing 'file'\n"
	"select: missing target chunk\n"
	"select: missing 'of'\n"
	"select: bad target chunk\n"
	"selectedButton: missing 'family'\n"
	"selectedButton: bad card expression\n"
	"send: bad message or expression\n"
	"send: bad event type expression\n"
	"send: bad target chunk or program expression\n"
	"set: error in expression\n"
	"set: no property specified\n"
	"set: missing 'the'\n"
	"set: missing 'to'\n"
	"setRegistry: bad parameter expression\n"
	"shell: bad parameter\n"
	"shortFilePath: bad file expression\n"
	"show: error visual effect expression\n"
	"show: error in location expression\n"
	"show: error in object expression\n"
	"sin: bad parameter\n"
	"sort: bad expression\n"
	"sort: error in object expression\n"
	"sort: no object specified\n"
	"specialFolderPath: bad type expression\n"
	"sqrt: bad parameter\n"
	"start: error in chunk expression\n"
	"start: bad action (should be 'editing' or 'using')\n"
	"start: no action specified ('editing' or 'using')\n"
	"Commands: not a valid object expression\n"
	"Commands: bad 'in' expression\n"
	"Commands: not a modifier key\n"
	"Commands: bad parameter\n"
	"Commands: bad parameters\n"
	"Commands: missing ','\n"
	"Commands: missing modifier key\n"
	"Commands: expected 'and'\n"
	"Commands: expected ','\n"
	"stdDev: bad parameters\n"
	"stop: error in chunk expression\n"
	"stop: bad action (must be editing, moving, playing, or using)\n"
	"stop: no action (must be editing, moving, playing, or using)\n"
	"subtract: bad destination\n"
	"subtract: bad expression\n"
	"subtract: missing 'from'\n"
	"Stack: bad stack expression\n"
	"sum: bad parameter\n"
	"switch: bad 'case' condition\n"
	"switch: bad condition\n"
	"switch: error in command\n"
	"switch: garbage where a command should be\n"
	"switch: not a command\n"
	"switch: missing 'end switch'\n"
	"tan: bad parameter\n"
	"Operators there: bad file expression\n"
	"Operators there: missing 'is'\n"
	"Operators there: no object specified\n"
	"throw: bad error expression\n"
	"toLower: bad parameter\n"
	"topStack: bad parameter\n"
	"toUpper: bad parameter\n"
	"transpose: bad variable parameter\n"
	"trunc: bad parameter\n"
	"try: error in command\n"
	"try: garbage where a command should be\n"
	"try: not a command\n"
	"try: missing 'end try'\n"
	"type: bad string expression\n"
	"ungroup: bad group expression\n"
	"uniDecode: bad parameter\n"
	"uniEncode: bad parameter\n"
	"unload: bad url expression\n"
	"unlock: not a visual effect\n"
	"unlock: no type specified ('screen', 'recent' or 'messages')\n"
	"unlock: bad type specified ('screen', 'recent' or 'messages')\n"
	"urlDecode: bad parameter\n"
	"urlEncode: bad parameter\n"
	"urlStatus: bad url expression\n"
	"value: bad parameter\n"
	"value: bad object expression\n"
	"Array: bad index\n"
	"Array: missing ']'\n"
	"visual: double directions specified\n"
	"visual: double effect specified\n"
	"visual: expected visual name\n"
	"visual: missing visual name\n"
	"visual: not a visual name\n"
	"wait: error in condition expression\n"
	"wait: no duration expression\n"
	"within: bad object expression\n"
	"within: bad point expression\n"
	"write: bad 'at' expression\n"
	"write: error in source expression\n"
	"write: bad file name\n"
	"write: bad destination (should be 'file or process')\n"
	"write: missing 'to'\n"
	"write: no destination (should be 'file or process')\n"
	"encrypt/decrypt: source container expected, but not supplied\n"
	"encrypt/decrypt: cipher name expected, but not supplied\n"
	"encrypt/decrypt: key expected, but not supplied\n"
	"encrypt/decrypt: 'at' clause supplied, but trailing 'bit' missing\n"
	"encrypt/decrypt: error parsing source container\n"
	"encrypt/decrypt: error parsing cipher expression\n"
	"encrypt/decrypt: error parsing key expression\n"
	"encrypt/decrypt: error parsing salt expression\n"
	"encrypt/decrypt: error parsing IV expression\n"
	"encrypt/decrypt: error parsing bit expression\n"
	"encrypt/decrypt: invalid clause supplied in this context\n"
	"visual: no parameter\n"
	"visual: bad parameter\n"
	"private: pass not valid in context\n"
	"begins/ends with: bad parameter\n"
	"numtobyte: bad parameter\n"
	"bytetonum: bad parameter\n"
	"arraydecode: bad parameter\n"
	"arrayencode: bad parameter\n"
	"dispatch: bad message\n"
	"dispatch: bad parameters\n"
	"dispatch: bad target\n"
	"do: unknown target environment\n"
	"export: bad palette type\n"
	"printing: missing destination\n"
	"printing: missing filename\n"
	"printing: bad options expression\n"
	"print: bad anchor name expression\n"
	"print: no anchor location expression\n"
	"print: bad anchor target expression\n"
	"print: no link location expression\n"
	"print: bad link target expression\n"
	"print: no link area expression\n"
	"print: bad link area expression\n"
	"Handler: repeated parameter name\n"
	"\n"
	"\n"
	"\n"
	"randomBytes: bad parameter expression\n"
	"sha1Digest: bad parameter expression\n"
	"print: bad bookmark title expression\n"
	"print: no bookmark level expression\n"
	"print: bad bookmark level expression\n"
	"print: bad bookmark location expression\n"
	"print: no bookmark expression\n"
	"print: bad bookmark initial state expression\n"
	"script: bad handler declaration\n"
	"script: illegal handler type in global script\n"
	"script: bad variable declaration\n"
	"script: bad statement\n"
	"script: not a statment\n"
	"script: bad command\n"
	"script: not a command\n"
	"script: unexpected eol\n"
	"script: illegal character\n"
	"include: bad filename expression\n"
	"require: bad filename expression\n"
	"echo: malformed implicit put\n"
	"lock: bad rect expression\n"
	"lock: missing 'rect' keyword\n"
	"relayer: bad source control\n"
	"relayer: invalid relation.\n"
	"relayer: bad target control\n"
	"controlAtLoc: bad location expression\n"
	"split/combine: bad form clause\n"
	"uuid: bad parameter list\n"
;

