NAME=libfoundation
TYPE=archive

include ../rules/environment.linux.makefile

SOURCES= \
	foundation-array.cpp \
	foundation-bidi.cpp \
	foundation-core.cpp \
	foundation-data.cpp \
	foundation-debug.cpp \
	foundation-error.cpp \
	foundation-filters.cpp \
	foundation-foreign.cpp \
	foundation-handler.cpp \
	foundation-list.cpp \
	foundation-locale.cpp \
	foundation-math.cpp \
	foundation-name.cpp \
	foundation-nativechars.cpp \
	foundation-number.cpp \
	foundation-pickle.cpp \
	foundation-proper-list.cpp \
	foundation-record.cpp \
	foundation-set.cpp \
	foundation-stream.cpp \
	foundation-string.cpp \
	foundation-text.cpp \
	foundation-typeconvert.cpp \
	foundation-typeinfo.cpp \
	foundation-unicodechars.cpp \
	foundation-unicode.cpp \
	foundation-value.cpp

CUSTOM_DEFINES=

CUSTOM_INCLUDES=./src

CUSTOM_CCFLAGS=-fno-exceptions -fno-rtti


include ../rules/archive.linux.makefile
