NAME=server-dbpostgresql
TYPE=library

include ../rules/environment.linux.makefile

SOURCES=\
	dbdrivercommon.cpp database.cpp dbpostgresqlapi.cpp postgresql_connection.cpp \
	postgresql_cursor.cpp

CUSTOM_DEFINES=_SERVER _LINUX_SERVER

CUSTOM_INCLUDES=./src

CUSTOM_LIBS=pq
CUSTOM_DYNAMIC_LIBS=

CUSTOM_CCFLAGS=\
	-Wall -Wno-non-virtual-dtor -fno-exceptions -fno-rtti \
	-fmessage-length=0

CUSTOM_LDFLAGS=

include ../rules/library.linux.makefile
