NAME=server-revdb
TYPE=library

include ../rules/environment.linux.makefile

SOURCES=revdb.cpp unxsupport.cpp database.cpp dbdrivercommon.cpp

CUSTOM_DEFINES=_SERVER _LINUX_SERVER

CUSTOM_INCLUDES=./src

CUSTOM_LIBS=external
CUSTOM_DYNAMIC_LIBS=dl

CUSTOM_CCFLAGS=\
	-Wall -Wno-non-virtual-dtor -fno-exceptions -fno-rtti \
	-fmessage-length=0

CUSTOM_LDFLAGS=

include ../rules/library.linux.makefile
