NAME=server-dbmysql
TYPE=library

SOURCES=\
	dbdrivercommon.cpp database.cpp dbmysqlapi.cpp mysql_connection.cpp \
	mysql_cursor.cpp

CUSTOM_DEFINES=_SERVER _LINUX_SERVER

CUSTOM_INCLUDES=./src

CUSTOM_LIBS=mysql
CUSTOM_STATIC_LIBS=stdc++ ssl crypto
CUSTOM_DYNAMIC_LIBS=pthread dl m z

CUSTOM_CCFLAGS=\
	-Wall -Wno-non-virtual-dtor -fno-exceptions -fno-rtti \
	-fmessage-length=0

CUSTOM_LDFLAGS=-L$(HOME)/revlibs/prefix/lib

include ../rules/library.linux.makefile
