# revDB Makefile

revdb:
	$(MAKE) -f Makefile.revdb revdb

server-revdb:
	$(MAKE) -f Makefile.server-revdb server-revdb

dbpostgresql:
	$(MAKE) -f Makefile.dbpostgresql dbpostgresql

server-dbpostgresql:
	$(MAKE) -f Makefile.server-dbpostgresql server-dbpostgresql

dbmysql:
	$(MAKE) -f Makefile.dbmysql dbmysql

server-dbmysql:
	$(MAKE) -f Makefile.server-dbmysql server-dbmysql

dbsqlite:
	$(MAKE) -f Makefile.dbsqlite dbsqlite

server-dbsqlite:
	$(MAKE) -f Makefile.server-dbsqlite server-dbsqlite

dbodbc:
	$(MAKE) -f Makefile.dbodbc dbodbc

server-dbodbc:
	$(MAKE) -f Makefile.server-dbodbc server-dbodbc
