NAME=dbmysql
TYPE=library

SOURCES=\
	dbdrivercommon.cpp database.cpp dbmysqlapi.cpp mysql_connection.cpp \
	mysql_cursor.cpp

CUSTOM_DEFINES=

CUSTOM_INCLUDES=./src

CUSTOM_LIBS=mysql z openssl
CUSTOM_STATIC_LIBS=stdc++
CUSTOM_DYNAMIC_LIBS=m pthread dl
CUSTOM_SHARED_LIBS=

CUSTOM_CCFLAGS=\
	-Wall -Wno-non-virtual-dtor -fno-exceptions -fno-rtti \
	-fmessage-length=0

CUSTOM_LDFLAGS=

include ../rules/library.linux.makefile
