NAME=dbsqlite
TYPE=library

include ../rules/environment.linux.makefile

SOURCES=\
	dbdrivercommon.cpp database.cpp dbsqliteapi.cpp sqlite_connection.cpp \
	sqlite_cursor.cpp

CUSTOM_DEFINES=

CUSTOM_INCLUDES=./src

CUSTOM_LIBS=sqlite external
CUSTOM_DYNAMIC_LIBS=pthread dl

CUSTOM_CCFLAGS=

CUSTOM_LDFLAGS=

include ../rules/library.linux.makefile
