NAME=server-dbodbc
TYPE=library

SOURCES=\
	dbdrivercommon.cpp database.cpp dbodbcapi.cpp odbc_connection.cpp \
	odbc_cursor.cpp

CUSTOM_DEFINES=_SERVER _LINUX_SERVER

CUSTOM_INCLUDES=./src

CUSTOM_LIBS=iodbc external
CUSTOM_STATIC_LIBS=stdc++
CUSTOM_DYNAMIC_LIBS=dl

CUSTOM_CCFLAGS=\
	-Wall -Wno-non-virtual-dtor -fno-exceptions -fno-rtti \
	-fmessage-length=0

CUSTOM_LDFLAGS=

include ../rules/library.linux.makefile
